### ISSUE TITLE
Videos for the updated documentation

### ISSUE THREAD

**Issue by Anam-Mahmood** [IBM/predict-insurance-charges-with-autoai#7]
video 12
![Edited 12- test the deployment](https://user-images.githubusercontent.com/54094367/111079973-cd4b3e80-8515-11eb-9446-5d52a90bbf0e.gif)

video 10
![Edited 10- promote to deployment and deploy](https://user-images.githubusercontent.com/54094367/111079975-cf150200-8515-11eb-8dc0-89b06f4b6aa5.gif)

video 9
![Edited 9- save as model and create deployment space](https://user-images.githubusercontent.com/54094367/111079977-cfad9880-8515-11eb-8a80-2e37cdc4b678.gif)
![Edited 8- Best pipeline and its features](https://user-images.githubusercontent.com/54094367/111079979-d1775c00-8515-11eb-97d3-7dfba7d85ff4.gif)

video 5
![Edited 5- add DS to project and show settings and run](https://user-images.githubusercontent.com/54094367/111079981-d20ff280-8515-11eb-914f-7c4eddaeadcb.gif)

video 4
![Edited 4- create an AutoAI project   ML instance](https://user-images.githubusercontent.com/54094367/111079982-d2a88900-8515-11eb-8b58-910c39785d27.gif)

video 3
![Edited 3- adding data set](https://user-images.githubusercontent.com/54094367/111079986-d4724c80-8515-11eb-8d55-89185c9add23.gif)

video 1
![Edited 1- creating watson studio service](https://user-images.githubusercontent.com/54094367/111079988-d50ae300-8515-11eb-8616-bec6485c140c.gif)

video 2
![Edited 2- creating an empty project](https://user-images.githubusercontent.com/54094367/111079989-d5a37980-8515-11eb-9cd0-cea012081dd3.gif)

image 6
<img width="1440" alt="6- pipeline completed " src="https://user-images.githubusercontent.com/54094367/111080010-e8b64980-8515-11eb-8feb-e464930ed949.png">

image 7
<img width="1440" alt="7- best pipeline view" src="https://user-images.githubusercontent.com/54094367/111080015-ebb13a00-8515-11eb-8cb2-b06d9b10c7dc.png">

image 1
<img width="1439" alt="11- deployment completed" src="https://user-images.githubusercontent.com/54094367/111080017-ece26700-8515-11eb-8b6d-7bb927b6bce8.png">

**Comment by mirzanauman** [comment]
Hay Anum , 
Good day , How are you . I am trying to Implement "IBM/predict-insurance-charges-with-autoai" since last couple of days but unfortunately i am stuck at a point and unable to get ridged from it. It is related to web deployment and i am stuck at point number 7.3
"7.3 Generate the access token
From the command line, type curl -V to verify if cURL is installed in your system. If cURL is not installed, refer to this instructions to get it installed.

Execute the following cURL command to generate your access token, but replace the apikey with the apikey you got from step 7.1 above.

curl -X POST 'https://iam.cloud.ibm.com/oidc/token' -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=<api-key-goes-here>'
As shown in the image below, the apikey can be copy and pasted from the downloaded file from the end of step 7.1. The curl request would look something like this after the apikey is pasted in:
"
I have checked i have installed cURL in my system. I have checked it. 
But unable to generate access token . Please help me . it would be a blessing for me . if we can have a online session just for 5 minutes . 
Need your help badly. 
Thanks in advance. 
Thanks and Regards, 
Nauman
